Vitalics common components
Hubses/ScienceFestival pull request #12
Opened 2017-07-10 06:55 UTC by vitalics

added missing typings

2017-07-10 07:43 UTC, DrJekill352 approved these changes

2017-07-10 13:25 UTC, ArtemVinogradov commented on festival/frontend/src/commonApp/button/button.component.html
> +<input type="text"> 123
sweet name for commit)

2017-07-10 17:52 UTC, mkinitcpio approved these changes

2017-07-11 07:42 UTC, zzz3bra commented on festival/frontend/src/commonApp/common.module.ts
> +<<<<<<< HEAD
resolve merge conflict maybe?

2017-07-11 07:43 UTC, zzz3bra requested changes
Resolve merge conflict in common.module.ts

2017-07-11 13:39 UTC, zzz3bra approved these changes
Will we use branching or now it is a deprecated technique?

2017-07-12 08:56 UTC, merged